In [1]:
import pandas as pd
import numpy as np

In [2]:
dfpd = pd.read_csv('https://github.com/magic-lantern/The-2024-Pediatric-Sepsis-Challenge/raw/refs/heads/main/SyntheticData_Training.csv', low_memory=False)
dfpd

,studyid_adm,agecalc_adm,height_cm_adm,weight_kg_adm,muac_mm_adm,hr_bpm_adm,rr_brpm_app_adm,sysbp_mmhg_adm,diasbp_mmhg_adm,temp_c_adm,...,cookloc_adm,lightfuel_adm,tobacco_adm,bednet_adm,hctpretransfusion_adm,hivstatus_adm,malariastatuspos_adm,lengthadm,caregiver_adm_new,inhospital_mortality
0,1,16.8,79.8,11.6,150.0,130.0,23.0,92.0,54.0,36.3,...,In a separate building/building space used as ...,Electric bulbs (national grid),Never,Always,Yes,HIV negative,No,2,Mother,0
1,2,46.1,93.0,13.6,151.0,115.0,35.0,72.0,42.0,36.8,...,In a separate building/building space used as ...,Tadooba,Never,Always,Yes,HIV negative,Yes,5,Mother,0
2,3,7.9,68.2,8.2,148.0,150.0,56.0,94.0,51.0,37.2,...,In a separate building/building space used as ...,Tadooba,Never,Always,Yes,HIV negative,No,4,Mother,0
3,4,38.2,95.0,12.0,138.0,134.0,38.0,94.0,57.0,37.6,...,In the house where you sleep,Electric bulbs (national grid),Never,Always,NaN,HIV negative,Yes,5,Mother,0
4,5,16.1,83.0,12.0,165.0,163.0,61.0,107.0,73.0,38.7,...,Outdoors in the open,Electric bulbs (national grid),Never,Sometimes,Yes,HIV negative,Yes,7,Mother,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2681,2682,20.1,98.2,10.0,135.0,163.0,61.0,103.0,54.0,39.6,...,Outdoors in the open,Solar powered bulbs,Never,Always,Yes,HIV negative,No,3,Mother,0
2682,2683,26.8,82.3,10.0,140.0,115.0,37.0,83.0,50.0,37.1,...,Outdoors in the open,Electric bulbs (national grid),Never,Sometimes,NaN,HIV negative,No,3,Mother,0
2683,2684,14.6,82.4,12.7,145.0,150.0,40.0,93.0,35.0,38.5,...,In a separate building/building space used as ...,Electric bulbs (national grid),Never,Always,Yes,HIV negative,Yes,2,Mother,0
2684,2685,9.5,67.5,7.5,130.0,145.0,26.0,88.0,52.0,37.3,...,In a separate building/building space used as ...,Solar powered bulbs,Never,Always,Yes,HIV negative,No,4,Mother,0
2685,2686,11.3,77.8,8.0,131.0,146.0,38.0,112.0,72.0,38.1,...,In a separate building/building space used as ...,Electric bulbs (national grid),Never,Always,Yes,HIV negative,Yes,2,Mother,0

In [3]:
pd.read_csv('../SyntheticData_Training.csv', low_memory=False)

,studyid_adm,agecalc_adm,height_cm_adm,weight_kg_adm,muac_mm_adm,hr_bpm_adm,rr_brpm_app_adm,sysbp_mmhg_adm,diasbp_mmhg_adm,temp_c_adm,...,cookloc_adm,lightfuel_adm,tobacco_adm,bednet_adm,hctpretransfusion_adm,hivstatus_adm,malariastatuspos_adm,lengthadm,caregiver_adm_new,inhospital_mortality
0,1,16.8,79.8,11.6,150.0,130.0,23.0,92.0,54.0,36.3,...,In a separate building/building space used as ...,Electric bulbs (national grid),Never,Always,Yes,HIV negative,No,2,Mother,0
1,2,46.1,93.0,13.6,151.0,115.0,35.0,72.0,42.0,36.8,...,In a separate building/building space used as ...,Tadooba,Never,Always,Yes,HIV negative,Yes,5,Mother,0
2,3,7.9,68.2,8.2,148.0,150.0,56.0,94.0,51.0,37.2,...,In a separate building/building space used as ...,Tadooba,Never,Always,Yes,HIV negative,No,4,Mother,0
3,4,38.2,95.0,12.0,138.0,134.0,38.0,94.0,57.0,37.6,...,In the house where you sleep,Electric bulbs (national grid),Never,Always,NaN,HIV negative,Yes,5,Mother,0
4,5,16.1,83.0,12.0,165.0,163.0,61.0,107.0,73.0,38.7,...,Outdoors in the open,Electric bulbs (national grid),Never,Sometimes,Yes,HIV negative,Yes,7,Mother,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2681,2682,20.1,98.2,10.0,135.0,163.0,61.0,103.0,54.0,39.6,...,Outdoors in the open,Solar powered bulbs,Never,Always,Yes,HIV negative,No,3,Mother,0
2682,2683,26.8,82.3,10.0,140.0,115.0,37.0,83.0,50.0,37.1,...,Outdoors in the open,Electric bulbs (national grid),Never,Sometimes,NaN,HIV negative,No,3,Mother,0
2683,2684,14.6,82.4,12.7,145.0,150.0,40.0,93.0,35.0,38.5,...,In a separate building/building space used as ...,Electric bulbs (national grid),Never,Always,Yes,HIV negative,Yes,2,Mother,0
2684,2685,9.5,67.5,7.5,130.0,145.0,26.0,88.0,52.0,37.3,...,In a separate building/building space used as ...,Solar powered bulbs,Never,Always,Yes,HIV negative,No,4,Mother,0
2685,2686,11.3,77.8,8.0,131.0,146.0,38.0,112.0,72.0,38.1,...,In a separate building/building space used as ...,Electric bulbs (national grid),Never,Always,Yes,HIV negative,Yes,2,Mother,0

In [5]:
!pip install polars

Collecting polars
  Downloading polars-1.13.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (14 kB)
Downloading polars-1.13.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (35.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.3/35.3 MB 114.7 MB/s eta 0:00:00a 0:00:01
Installing collected packages: polars
Successfully installed polars-1.13.0

In [6]:
import polars as pl

In [7]:
dfpl = pl.read_csv('https://github.com/magic-lantern/The-2024-Pediatric-Sepsis-Challenge/raw/refs/heads/main/SyntheticData_Training.csv', infer_schema_length=1000000)
dfpl

shape: (2_686, 140)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ studyid_a ┆ agecalc_a ┆ height_cm ┆ weight_kg ┆ … ┆ malariast ┆ lengthadm ┆ caregiver ┆ inhospit │
│ dm        ┆ dm        ┆ _adm      ┆ _adm      ┆   ┆ atuspos_a ┆ ---       ┆ _adm_new  ┆ al_morta │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ dm        ┆ i64       ┆ ---       ┆ lity     │
│ i64       ┆ f64       ┆ str       ┆ str       ┆   ┆ ---       ┆           ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 16.8      ┆ 79.8      ┆ 11.6      ┆ … ┆ No        ┆ 2         ┆ Mother    ┆ 0        │
│ 2         ┆ 46.1      ┆ 93        ┆ 13.6      ┆ … ┆ Yes       ┆ 5         ┆ Mother    ┆ 0        │
│ 3         ┆ 7.9       ┆ 68.2      ┆ 8.2       ┆ … ┆ No        ┆ 4         ┆ Mother    ┆ 0        │
│ 4         ┆ 38.2      ┆ 95        ┆ 12        ┆ … ┆ Yes       ┆ 5         ┆ Mother    ┆ 0        │
│ 5         ┆ 16.1      ┆ 83        ┆ 12        ┆ … ┆ Yes       ┆ 7         ┆ Mother    ┆ 0        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2682      ┆ 20.1      ┆ 98.2      ┆ 10        ┆ … ┆ No        ┆ 3         ┆ Mother    ┆ 0        │
│ 2683      ┆ 26.8      ┆ 82.3      ┆ 10        ┆ … ┆ No        ┆ 3         ┆ Mother    ┆ 0        │
│ 2684      ┆ 14.6      ┆ 82.4      ┆ 12.7      ┆ … ┆ Yes       ┆ 2         ┆ Mother    ┆ 0        │
│ 2685      ┆ 9.5       ┆ 67.5      ┆ 7.5       ┆ … ┆ No        ┆ 4         ┆ Mother    ┆ 0        │
│ 2686      ┆ 11.3      ┆ 77.8      ┆ 8         ┆ … ┆ Yes       ┆ 2         ┆ Mother    ┆ 0        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
pl.read_csv('../SyntheticData_Training.csv',
            low_memory=False,
            null_values=['NA'],
            infer_schema_length=100000
           )

shape: (2_686, 140)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ studyid_a ┆ agecalc_a ┆ height_cm ┆ weight_kg ┆ … ┆ malariast ┆ lengthadm ┆ caregiver ┆ inhospit │
│ dm        ┆ dm        ┆ _adm      ┆ _adm      ┆   ┆ atuspos_a ┆ ---       ┆ _adm_new  ┆ al_morta │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ dm        ┆ i64       ┆ ---       ┆ lity     │
│ i64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆           ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 16.8      ┆ 79.8      ┆ 11.6      ┆ … ┆ No        ┆ 2         ┆ Mother    ┆ 0        │
│ 2         ┆ 46.1      ┆ 93.0      ┆ 13.6      ┆ … ┆ Yes       ┆ 5         ┆ Mother    ┆ 0        │
│ 3         ┆ 7.9       ┆ 68.2      ┆ 8.2       ┆ … ┆ No        ┆ 4         ┆ Mother    ┆ 0        │
│ 4         ┆ 38.2      ┆ 95.0      ┆ 12.0      ┆ … ┆ Yes       ┆ 5         ┆ Mother    ┆ 0        │
│ 5         ┆ 16.1      ┆ 83.0      ┆ 12.0      ┆ … ┆ Yes       ┆ 7         ┆ Mother    ┆ 0        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2682      ┆ 20.1      ┆ 98.2      ┆ 10.0      ┆ … ┆ No        ┆ 3         ┆ Mother    ┆ 0        │
│ 2683      ┆ 26.8      ┆ 82.3      ┆ 10.0      ┆ … ┆ No        ┆ 3         ┆ Mother    ┆ 0        │
│ 2684      ┆ 14.6      ┆ 82.4      ┆ 12.7      ┆ … ┆ Yes       ┆ 2         ┆ Mother    ┆ 0        │
│ 2685      ┆ 9.5       ┆ 67.5      ┆ 7.5       ┆ … ┆ No        ┆ 4         ┆ Mother    ┆ 0        │
│ 2686      ┆ 11.3      ┆ 77.8      ┆ 8.0       ┆ … ┆ Yes       ┆ 2         ┆ Mother    ┆ 0        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘